// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (user_id, token_hash, expires_at, user_agent)
VALUES ($1::uuid, $2, $3, $4)
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserAgent pgtype.Text        `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	return err
}

const getUserBySession = `-- name: GetUserBySession :one
SELECT
    users.id::text AS id,
    users.email,
    users.display_name,
    users.timezone,
    users.functional_currency,
    users.display_currency,
    users.onboarding_completed
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.expires_at > now()
LIMIT 1
`

type GetUserBySessionRow struct {
	ID                  string `json:"id"`
	Email               string `json:"email"`
	DisplayName         string `json:"display_name"`
	Timezone            string `json:"timezone"`
	FunctionalCurrency  string `json:"functional_currency"`
	DisplayCurrency     string `json:"display_currency"`
	OnboardingCompleted bool   `json:"onboarding_completed"`
}

func (q *Queries) GetUserBySession(ctx context.Context, tokenHash []byte) (GetUserBySessionRow, error) {
	row := q.db.QueryRow(ctx, getUserBySession, tokenHash)
	var i GetUserBySessionRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.FunctionalCurrency,
		&i.DisplayCurrency,
		&i.OnboardingCompleted,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT
    id::text AS id,
    email,
    display_name,
    password_hash,
    timezone,
    functional_currency,
    display_currency,
    onboarding_completed
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserForLoginRow struct {
	ID                  string `json:"id"`
	Email               string `json:"email"`
	DisplayName         string `json:"display_name"`
	PasswordHash        string `json:"password_hash"`
	Timezone            string `json:"timezone"`
	FunctionalCurrency  string `json:"functional_currency"`
	DisplayCurrency     string `json:"display_currency"`
	OnboardingCompleted bool   `json:"onboarding_completed"`
}

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Timezone,
		&i.FunctionalCurrency,
		&i.DisplayCurrency,
		&i.OnboardingCompleted,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}
