// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeUserOnboarding = `-- name: CompleteUserOnboarding :one
UPDATE users
SET timezone = $1,
    functional_currency = $2,
    display_currency = $3,
    reconciliation_mode = $4,
    onboarding_completed = true,
    updated_at = now()
WHERE id = $5::uuid
RETURNING
    id::text AS id,
    email,
    display_name,
    timezone,
    functional_currency,
    display_currency,
    reconciliation_mode,
    onboarding_completed
`

type CompleteUserOnboardingParams struct {
	Timezone           string      `json:"timezone"`
	FunctionalCurrency string      `json:"functional_currency"`
	DisplayCurrency    string      `json:"display_currency"`
	ReconciliationMode string      `json:"reconciliation_mode"`
	UserID             pgtype.UUID `json:"user_id"`
}

type CompleteUserOnboardingRow struct {
	ID                  string `json:"id"`
	Email               string `json:"email"`
	DisplayName         string `json:"display_name"`
	Timezone            string `json:"timezone"`
	FunctionalCurrency  string `json:"functional_currency"`
	DisplayCurrency     string `json:"display_currency"`
	ReconciliationMode  string `json:"reconciliation_mode"`
	OnboardingCompleted bool   `json:"onboarding_completed"`
}

func (q *Queries) CompleteUserOnboarding(ctx context.Context, arg CompleteUserOnboardingParams) (CompleteUserOnboardingRow, error) {
	row := q.db.QueryRow(ctx, completeUserOnboarding,
		arg.Timezone,
		arg.FunctionalCurrency,
		arg.DisplayCurrency,
		arg.ReconciliationMode,
		arg.UserID,
	)
	var i CompleteUserOnboardingRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.FunctionalCurrency,
		&i.DisplayCurrency,
		&i.ReconciliationMode,
		&i.OnboardingCompleted,
	)
	return i, err
}

const consumeLoginChallenge = `-- name: ConsumeLoginChallenge :exec
UPDATE login_challenges
SET consumed_at = now()
WHERE id = $1::uuid
  AND consumed_at IS NULL
`

func (q *Queries) ConsumeLoginChallenge(ctx context.Context, challengeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, consumeLoginChallenge, challengeID)
	return err
}

const countActiveRecoveryCodes = `-- name: CountActiveRecoveryCodes :one
SELECT count(*)
FROM recovery_codes
WHERE user_id = $1::uuid
  AND used_at IS NULL
`

func (q *Queries) CountActiveRecoveryCodes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthAuditEvent = `-- name: CreateAuthAuditEvent :exec
INSERT INTO auth_audit_events (user_id, event_type, success, request_id, metadata)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5
)
`

type CreateAuthAuditEventParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EventType string      `json:"event_type"`
	Success   bool        `json:"success"`
	RequestID pgtype.Text `json:"request_id"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateAuthAuditEvent(ctx context.Context, arg CreateAuthAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuthAuditEvent,
		arg.UserID,
		arg.EventType,
		arg.Success,
		arg.RequestID,
		arg.Metadata,
	)
	return err
}

const createLoginChallenge = `-- name: CreateLoginChallenge :exec
INSERT INTO login_challenges (user_id, token_hash, expires_at)
VALUES ($1::uuid, $2, $3)
`

type CreateLoginChallengeParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateLoginChallenge(ctx context.Context, arg CreateLoginChallengeParams) error {
	_, err := q.db.Exec(ctx, createLoginChallenge, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createOnboardingAccountSetup = `-- name: CreateOnboardingAccountSetup :one
INSERT INTO onboarding_account_setups (
    user_id,
    name,
    account_class,
    subtype,
    currency,
    opening_balance,
    opening_balance_date
)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id::text
`

type CreateOnboardingAccountSetupParams struct {
	UserID             pgtype.UUID    `json:"user_id"`
	Name               string         `json:"name"`
	AccountClass       string         `json:"account_class"`
	Subtype            string         `json:"subtype"`
	Currency           string         `json:"currency"`
	OpeningBalance     pgtype.Numeric `json:"opening_balance"`
	OpeningBalanceDate pgtype.Date    `json:"opening_balance_date"`
}

func (q *Queries) CreateOnboardingAccountSetup(ctx context.Context, arg CreateOnboardingAccountSetupParams) (string, error) {
	row := q.db.QueryRow(ctx, createOnboardingAccountSetup,
		arg.UserID,
		arg.Name,
		arg.AccountClass,
		arg.Subtype,
		arg.Currency,
		arg.OpeningBalance,
		arg.OpeningBalanceDate,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createOnboardingRecurringIncomeSetup = `-- name: CreateOnboardingRecurringIncomeSetup :one
INSERT INTO onboarding_recurring_income_setups (
    user_id,
    name,
    amount,
    currency,
    day_of_month
)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5
)
RETURNING id::text
`

type CreateOnboardingRecurringIncomeSetupParams struct {
	UserID     pgtype.UUID    `json:"user_id"`
	Name       string         `json:"name"`
	Amount     pgtype.Numeric `json:"amount"`
	Currency   string         `json:"currency"`
	DayOfMonth int16          `json:"day_of_month"`
}

func (q *Queries) CreateOnboardingRecurringIncomeSetup(ctx context.Context, arg CreateOnboardingRecurringIncomeSetupParams) (string, error) {
	row := q.db.QueryRow(ctx, createOnboardingRecurringIncomeSetup,
		arg.UserID,
		arg.Name,
		arg.Amount,
		arg.Currency,
		arg.DayOfMonth,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :exec
INSERT INTO recovery_codes (user_id, code_hash)
VALUES ($1::uuid, $2)
`

type CreateRecoveryCodeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	CodeHash []byte      `json:"code_hash"`
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, createRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at, user_agent)
VALUES ($1::uuid, $2, $3, $4)
RETURNING id::text
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserAgent pgtype.Text        `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, password_hash)
VALUES ($1, $2, $3)
RETURNING
    id::text AS id,
    email,
    display_name,
    timezone,
    functional_currency,
    display_currency,
    reconciliation_mode,
    onboarding_completed
`

type CreateUserParams struct {
	Email        string `json:"email"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID                  string `json:"id"`
	Email               string `json:"email"`
	DisplayName         string `json:"display_name"`
	Timezone            string `json:"timezone"`
	FunctionalCurrency  string `json:"functional_currency"`
	DisplayCurrency     string `json:"display_currency"`
	ReconciliationMode  string `json:"reconciliation_mode"`
	OnboardingCompleted bool   `json:"onboarding_completed"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.FunctionalCurrency,
		&i.DisplayCurrency,
		&i.ReconciliationMode,
		&i.OnboardingCompleted,
	)
	return i, err
}

const deleteExpiredLoginChallenges = `-- name: DeleteExpiredLoginChallenges :execrows
DELETE FROM login_challenges
WHERE expires_at < now() - interval '1 day'
   OR consumed_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredLoginChallenges(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLoginChallenges)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at < now() - interval '7 days'
   OR revoked_at < now() - interval '30 days'
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM recovery_codes WHERE user_id = $1::uuid
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1::uuid
`

func (q *Queries) DeleteUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const disableTOTP = `-- name: DisableTOTP :exec
DELETE FROM totp_credentials
WHERE user_id = $1::uuid
`

func (q *Queries) DisableTOTP(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableTOTP, userID)
	return err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE totp_credentials
SET enabled_at = now(),
    updated_at = now()
WHERE user_id = $1::uuid
  AND enabled_at IS NULL
`

func (q *Queries) EnableTOTP(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, enableTOTP, userID)
	return err
}

const getLoginChallengeForUpdate = `-- name: GetLoginChallengeForUpdate :one
SELECT
    login_challenges.id::text AS challenge_id,
    login_challenges.user_id::text AS user_id,
    login_challenges.attempts,
    users.email,
    users.display_name,
    users.timezone,
    users.functional_currency,
    users.display_currency,
    users.reconciliation_mode,
    users.onboarding_completed,
    totp_credentials.secret_ciphertext,
    totp_credentials.last_used_step
FROM login_challenges
JOIN users ON users.id = login_challenges.user_id
JOIN totp_credentials ON totp_credentials.user_id = users.id
WHERE login_challenges.token_hash = $1
  AND login_challenges.consumed_at IS NULL
  AND login_challenges.expires_at > now()
  AND login_challenges.attempts < 5
  AND totp_credentials.enabled_at IS NOT NULL
FOR UPDATE OF login_challenges, totp_credentials
`

type GetLoginChallengeForUpdateRow struct {
	ChallengeID         string `json:"challenge_id"`
	UserID              string `json:"user_id"`
	Attempts            int16  `json:"attempts"`
	Email               string `json:"email"`
	DisplayName         string `json:"display_name"`
	Timezone            string `json:"timezone"`
	FunctionalCurrency  string `json:"functional_currency"`
	DisplayCurrency     string `json:"display_currency"`
	ReconciliationMode  string `json:"reconciliation_mode"`
	OnboardingCompleted bool   `json:"onboarding_completed"`
	SecretCiphertext    []byte `json:"secret_ciphertext"`
	LastUsedStep        int64  `json:"last_used_step"`
}

func (q *Queries) GetLoginChallengeForUpdate(ctx context.Context, tokenHash []byte) (GetLoginChallengeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLoginChallengeForUpdate, tokenHash)
	var i GetLoginChallengeForUpdateRow
	err := row.Scan(
		&i.ChallengeID,
		&i.UserID,
		&i.Attempts,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.FunctionalCurrency,
		&i.DisplayCurrency,
		&i.ReconciliationMode,
		&i.OnboardingCompleted,
		&i.SecretCiphertext,
		&i.LastUsedStep,
	)
	return i, err
}

const getRecoveryCodeForUpdate = `-- name: GetRecoveryCodeForUpdate :one
SELECT id::text AS id
FROM recovery_codes
WHERE user_id = $1::uuid
  AND code_hash = $2
  AND used_at IS NULL
FOR UPDATE
`

type GetRecoveryCodeForUpdateParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	CodeHash []byte      `json:"code_hash"`
}

func (q *Queries) GetRecoveryCodeForUpdate(ctx context.Context, arg GetRecoveryCodeForUpdateParams) (string, error) {
	row := q.db.QueryRow(ctx, getRecoveryCodeForUpdate, arg.UserID, arg.CodeHash)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getTOTPForUser = `-- name: GetTOTPForUser :one
SELECT secret_ciphertext, enabled_at, last_used_step
FROM totp_credentials
WHERE user_id = $1::uuid
FOR UPDATE
`

type GetTOTPForUserRow struct {
	SecretCiphertext []byte             `json:"secret_ciphertext"`
	EnabledAt        pgtype.Timestamptz `json:"enabled_at"`
	LastUsedStep     int64              `json:"last_used_step"`
}

func (q *Queries) GetTOTPForUser(ctx context.Context, userID pgtype.UUID) (GetTOTPForUserRow, error) {
	row := q.db.QueryRow(ctx, getTOTPForUser, userID)
	var i GetTOTPForUserRow
	err := row.Scan(&i.SecretCiphertext, &i.EnabledAt, &i.LastUsedStep)
	return i, err
}

const getUserBySession = `-- name: GetUserBySession :one
SELECT
    sessions.id::text AS session_id,
    users.id::text AS id,
    users.email,
    users.display_name,
    users.timezone,
    users.functional_currency,
    users.display_currency,
    users.reconciliation_mode,
    users.onboarding_completed,
    (totp_credentials.enabled_at IS NOT NULL)::boolean AS totp_enabled
FROM sessions
JOIN users ON users.id = sessions.user_id
LEFT JOIN totp_credentials ON totp_credentials.user_id = users.id
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.expires_at > now()
LIMIT 1
`

type GetUserBySessionRow struct {
	SessionID           string `json:"session_id"`
	ID                  string `json:"id"`
	Email               string `json:"email"`
	DisplayName         string `json:"display_name"`
	Timezone            string `json:"timezone"`
	FunctionalCurrency  string `json:"functional_currency"`
	DisplayCurrency     string `json:"display_currency"`
	ReconciliationMode  string `json:"reconciliation_mode"`
	OnboardingCompleted bool   `json:"onboarding_completed"`
	TotpEnabled         bool   `json:"totp_enabled"`
}

func (q *Queries) GetUserBySession(ctx context.Context, tokenHash []byte) (GetUserBySessionRow, error) {
	row := q.db.QueryRow(ctx, getUserBySession, tokenHash)
	var i GetUserBySessionRow
	err := row.Scan(
		&i.SessionID,
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.FunctionalCurrency,
		&i.DisplayCurrency,
		&i.ReconciliationMode,
		&i.OnboardingCompleted,
		&i.TotpEnabled,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT
    users.id::text AS id,
    users.email,
    users.display_name,
    users.password_hash,
    users.timezone,
    users.functional_currency,
    users.display_currency,
    users.reconciliation_mode,
    users.onboarding_completed,
    (totp_credentials.enabled_at IS NOT NULL)::boolean AS totp_enabled
FROM users
LEFT JOIN totp_credentials ON totp_credentials.user_id = users.id
WHERE users.email = $1
LIMIT 1
`

type GetUserForLoginRow struct {
	ID                  string `json:"id"`
	Email               string `json:"email"`
	DisplayName         string `json:"display_name"`
	PasswordHash        string `json:"password_hash"`
	Timezone            string `json:"timezone"`
	FunctionalCurrency  string `json:"functional_currency"`
	DisplayCurrency     string `json:"display_currency"`
	ReconciliationMode  string `json:"reconciliation_mode"`
	OnboardingCompleted bool   `json:"onboarding_completed"`
	TotpEnabled         bool   `json:"totp_enabled"`
}

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Timezone,
		&i.FunctionalCurrency,
		&i.DisplayCurrency,
		&i.ReconciliationMode,
		&i.OnboardingCompleted,
		&i.TotpEnabled,
	)
	return i, err
}

const getUserSecurityForUpdate = `-- name: GetUserSecurityForUpdate :one
SELECT id::text AS id, email, display_name, password_hash
FROM users
WHERE id = $1::uuid
FOR UPDATE
`

type GetUserSecurityForUpdateRow struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) GetUserSecurityForUpdate(ctx context.Context, userID pgtype.UUID) (GetUserSecurityForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserSecurityForUpdate, userID)
	var i GetUserSecurityForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
	)
	return i, err
}

const incrementLoginChallengeAttempts = `-- name: IncrementLoginChallengeAttempts :exec
UPDATE login_challenges
SET attempts = attempts + 1
WHERE id = $1::uuid
`

func (q *Queries) IncrementLoginChallengeAttempts(ctx context.Context, challengeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementLoginChallengeAttempts, challengeID)
	return err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT
    id::text AS id,
    created_at,
    last_seen_at,
    expires_at,
    user_agent,
    token_hash = $1 AS current
FROM sessions
WHERE user_id = $2::uuid
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY current DESC, last_seen_at DESC
`

type ListUserSessionsParams struct {
	CurrentTokenHash []byte      `json:"current_token_hash"`
	UserID           pgtype.UUID `json:"user_id"`
}

type ListUserSessionsRow struct {
	ID         string             `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Current    bool               `json:"current"`
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, arg.CurrentTokenHash, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSessionsRow{}
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.UserAgent,
			&i.Current,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserForOnboarding = `-- name: LockUserForOnboarding :one
SELECT onboarding_completed
FROM users
WHERE id = $1::uuid
FOR UPDATE
`

func (q *Queries) LockUserForOnboarding(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, lockUserForOnboarding, userID)
	var onboarding_completed bool
	err := row.Scan(&onboarding_completed)
	return onboarding_completed, err
}

const revokeOtherUserSessions = `-- name: RevokeOtherUserSessions :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1::uuid
  AND token_hash <> $2
  AND revoked_at IS NULL
`

type RevokeOtherUserSessionsParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	CurrentTokenHash []byte      `json:"current_token_hash"`
}

func (q *Queries) RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherUserSessions, arg.UserID, arg.CurrentTokenHash)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :one
UPDATE sessions
SET revoked_at = now()
WHERE id = $1::uuid
  AND user_id = $2::uuid
  AND revoked_at IS NULL
RETURNING token_hash
`

type RevokeUserSessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, revokeUserSession, arg.SessionID, arg.UserID)
	var token_hash []byte
	err := row.Scan(&token_hash)
	return token_hash, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = now()
WHERE token_hash = $1
  AND last_seen_at < now() - interval '5 minutes'
`

func (q *Queries) TouchSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, touchSession, tokenHash)
	return err
}

const updateTOTPLastUsedStep = `-- name: UpdateTOTPLastUsedStep :exec
UPDATE totp_credentials
SET last_used_step = $1,
    updated_at = now()
WHERE user_id = $2::uuid
  AND last_used_step < $1
`

type UpdateTOTPLastUsedStepParams struct {
	LastUsedStep int64       `json:"last_used_step"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateTOTPLastUsedStep(ctx context.Context, arg UpdateTOTPLastUsedStepParams) error {
	_, err := q.db.Exec(ctx, updateTOTPLastUsedStep, arg.LastUsedStep, arg.UserID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1,
    password_changed_at = now(),
    updated_at = now()
WHERE id = $2::uuid
`

type UpdateUserPasswordParams struct {
	PasswordHash string      `json:"password_hash"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.UserID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET email = $1,
    display_name = $2,
    updated_at = now()
WHERE id = $3::uuid
RETURNING
    id::text AS id,
    email,
    display_name,
    timezone,
    functional_currency,
    display_currency,
    reconciliation_mode,
    onboarding_completed
`

type UpdateUserProfileParams struct {
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
	UserID      pgtype.UUID `json:"user_id"`
}

type UpdateUserProfileRow struct {
	ID                  string `json:"id"`
	Email               string `json:"email"`
	DisplayName         string `json:"display_name"`
	Timezone            string `json:"timezone"`
	FunctionalCurrency  string `json:"functional_currency"`
	DisplayCurrency     string `json:"display_currency"`
	ReconciliationMode  string `json:"reconciliation_mode"`
	OnboardingCompleted bool   `json:"onboarding_completed"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.Email, arg.DisplayName, arg.UserID)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.FunctionalCurrency,
		&i.DisplayCurrency,
		&i.ReconciliationMode,
		&i.OnboardingCompleted,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE users
SET timezone = $1,
    functional_currency = $2,
    display_currency = $3,
    reconciliation_mode = $4,
    updated_at = now()
WHERE id = $5::uuid
RETURNING
    id::text AS id,
    email,
    display_name,
    timezone,
    functional_currency,
    display_currency,
    reconciliation_mode,
    onboarding_completed
`

type UpdateUserSettingsParams struct {
	Timezone           string      `json:"timezone"`
	FunctionalCurrency string      `json:"functional_currency"`
	DisplayCurrency    string      `json:"display_currency"`
	ReconciliationMode string      `json:"reconciliation_mode"`
	UserID             pgtype.UUID `json:"user_id"`
}

type UpdateUserSettingsRow struct {
	ID                  string `json:"id"`
	Email               string `json:"email"`
	DisplayName         string `json:"display_name"`
	Timezone            string `json:"timezone"`
	FunctionalCurrency  string `json:"functional_currency"`
	DisplayCurrency     string `json:"display_currency"`
	ReconciliationMode  string `json:"reconciliation_mode"`
	OnboardingCompleted bool   `json:"onboarding_completed"`
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UpdateUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.Timezone,
		arg.FunctionalCurrency,
		arg.DisplayCurrency,
		arg.ReconciliationMode,
		arg.UserID,
	)
	var i UpdateUserSettingsRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.FunctionalCurrency,
		&i.DisplayCurrency,
		&i.ReconciliationMode,
		&i.OnboardingCompleted,
	)
	return i, err
}

const upsertPendingTOTP = `-- name: UpsertPendingTOTP :exec
INSERT INTO totp_credentials (user_id, secret_ciphertext)
VALUES ($1::uuid, $2)
ON CONFLICT (user_id) DO UPDATE
SET secret_ciphertext = EXCLUDED.secret_ciphertext,
    enabled_at = NULL,
    last_used_step = -1,
    updated_at = now()
`

type UpsertPendingTOTPParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	SecretCiphertext []byte      `json:"secret_ciphertext"`
}

func (q *Queries) UpsertPendingTOTP(ctx context.Context, arg UpsertPendingTOTPParams) error {
	_, err := q.db.Exec(ctx, upsertPendingTOTP, arg.UserID, arg.SecretCiphertext)
	return err
}

const useRecoveryCode = `-- name: UseRecoveryCode :exec
UPDATE recovery_codes
SET used_at = now()
WHERE id = $1::uuid
  AND used_at IS NULL
`

func (q *Queries) UseRecoveryCode(ctx context.Context, recoveryCodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, useRecoveryCode, recoveryCodeID)
	return err
}
