// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metadata.sql

package database

import (
	"context"
)

const getAppMetadata = `-- name: GetAppMetadata :one
SELECT key, value, updated_at
FROM app_metadata
WHERE key = $1
`

func (q *Queries) GetAppMetadata(ctx context.Context, key string) (AppMetadatum, error) {
	row := q.db.QueryRow(ctx, getAppMetadata, key)
	var i AppMetadatum
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const upsertAppMetadata = `-- name: UpsertAppMetadata :one
INSERT INTO app_metadata (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    updated_at = now()
RETURNING key, value, updated_at
`

type UpsertAppMetadataParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) UpsertAppMetadata(ctx context.Context, arg UpsertAppMetadataParams) (AppMetadatum, error) {
	row := q.db.QueryRow(ctx, upsertAppMetadata, arg.Key, arg.Value)
	var i AppMetadatum
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
