// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountSubtype.
const (
	AccountSubtypeBank       AccountSubtype = "bank"
	AccountSubtypeBrokerage  AccountSubtype = "brokerage"
	AccountSubtypeCash       AccountSubtype = "cash"
	AccountSubtypeLoan       AccountSubtype = "loan"
	AccountSubtypeMortgage   AccountSubtype = "mortgage"
	AccountSubtypeOther      AccountSubtype = "other"
	AccountSubtypeRealEstate AccountSubtype = "real_estate"
	AccountSubtypeSecurity   AccountSubtype = "security"
	AccountSubtypeVehicle    AccountSubtype = "vehicle"
)

// Valid indicates whether the value is a known member of the AccountSubtype enum.
func (e AccountSubtype) Valid() bool {
	switch e {
	case AccountSubtypeBank:
		return true
	case AccountSubtypeBrokerage:
		return true
	case AccountSubtypeCash:
		return true
	case AccountSubtypeLoan:
		return true
	case AccountSubtypeMortgage:
		return true
	case AccountSubtypeOther:
		return true
	case AccountSubtypeRealEstate:
		return true
	case AccountSubtypeSecurity:
		return true
	case AccountSubtypeVehicle:
		return true
	default:
		return false
	}
}

// Defines values for CategoryDirection.
const (
	CategoryDirectionEXPENSE CategoryDirection = "EXPENSE"
	CategoryDirectionINCOME  CategoryDirection = "INCOME"
)

// Valid indicates whether the value is a known member of the CategoryDirection enum.
func (e CategoryDirection) Valid() bool {
	switch e {
	case CategoryDirectionEXPENSE:
		return true
	case CategoryDirectionINCOME:
		return true
	default:
		return false
	}
}

// Defines values for CreateTransactionRequestType.
const (
	CreateTransactionRequestTypeASSETPURCHASE  CreateTransactionRequestType = "ASSET_PURCHASE"
	CreateTransactionRequestTypeEXPENSE        CreateTransactionRequestType = "EXPENSE"
	CreateTransactionRequestTypeINCOME         CreateTransactionRequestType = "INCOME"
	CreateTransactionRequestTypeOPENINGBALANCE CreateTransactionRequestType = "OPENING_BALANCE"
	CreateTransactionRequestTypeTRANSFER       CreateTransactionRequestType = "TRANSFER"
)

// Valid indicates whether the value is a known member of the CreateTransactionRequestType enum.
func (e CreateTransactionRequestType) Valid() bool {
	switch e {
	case CreateTransactionRequestTypeASSETPURCHASE:
		return true
	case CreateTransactionRequestTypeEXPENSE:
		return true
	case CreateTransactionRequestTypeINCOME:
		return true
	case CreateTransactionRequestTypeOPENINGBALANCE:
		return true
	case CreateTransactionRequestTypeTRANSFER:
		return true
	default:
		return false
	}
}

// Defines values for Currency.
const (
	AED Currency = "AED"
	AUD Currency = "AUD"
	BRL Currency = "BRL"
	CAD Currency = "CAD"
	CHF Currency = "CHF"
	CNY Currency = "CNY"
	DKK Currency = "DKK"
	EUR Currency = "EUR"
	GBP Currency = "GBP"
	HKD Currency = "HKD"
	INR Currency = "INR"
	JPY Currency = "JPY"
	KRW Currency = "KRW"
	KZT Currency = "KZT"
	MXN Currency = "MXN"
	NOK Currency = "NOK"
	NZD Currency = "NZD"
	RUB Currency = "RUB"
	SEK Currency = "SEK"
	SGD Currency = "SGD"
	TWD Currency = "TWD"
	UAH Currency = "UAH"
	USD Currency = "USD"
	ZAR Currency = "ZAR"
)

// Valid indicates whether the value is a known member of the Currency enum.
func (e Currency) Valid() bool {
	switch e {
	case AED:
		return true
	case AUD:
		return true
	case BRL:
		return true
	case CAD:
		return true
	case CHF:
		return true
	case CNY:
		return true
	case DKK:
		return true
	case EUR:
		return true
	case GBP:
		return true
	case HKD:
		return true
	case INR:
		return true
	case JPY:
		return true
	case KRW:
		return true
	case KZT:
		return true
	case MXN:
		return true
	case NOK:
		return true
	case NZD:
		return true
	case RUB:
		return true
	case SEK:
		return true
	case SGD:
		return true
	case TWD:
		return true
	case UAH:
		return true
	case USD:
		return true
	case ZAR:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for LoginChallengeResponseStatus.
const (
	TotpRequired LoginChallengeResponseStatus = "totp_required"
)

// Valid indicates whether the value is a known member of the LoginChallengeResponseStatus enum.
func (e LoginChallengeResponseStatus) Valid() bool {
	switch e {
	case TotpRequired:
		return true
	default:
		return false
	}
}

// Defines values for OnboardingAccountAccountClass.
const (
	OnboardingAccountAccountClassASSET     OnboardingAccountAccountClass = "ASSET"
	OnboardingAccountAccountClassLIABILITY OnboardingAccountAccountClass = "LIABILITY"
)

// Valid indicates whether the value is a known member of the OnboardingAccountAccountClass enum.
func (e OnboardingAccountAccountClass) Valid() bool {
	switch e {
	case OnboardingAccountAccountClassASSET:
		return true
	case OnboardingAccountAccountClassLIABILITY:
		return true
	default:
		return false
	}
}

// Defines values for OnboardingAccountSubtype.
const (
	OnboardingAccountSubtypeBank       OnboardingAccountSubtype = "bank"
	OnboardingAccountSubtypeBrokerage  OnboardingAccountSubtype = "brokerage"
	OnboardingAccountSubtypeCash       OnboardingAccountSubtype = "cash"
	OnboardingAccountSubtypeLoan       OnboardingAccountSubtype = "loan"
	OnboardingAccountSubtypeMortgage   OnboardingAccountSubtype = "mortgage"
	OnboardingAccountSubtypeOther      OnboardingAccountSubtype = "other"
	OnboardingAccountSubtypeRealEstate OnboardingAccountSubtype = "real_estate"
	OnboardingAccountSubtypeSecurity   OnboardingAccountSubtype = "security"
	OnboardingAccountSubtypeVehicle    OnboardingAccountSubtype = "vehicle"
)

// Valid indicates whether the value is a known member of the OnboardingAccountSubtype enum.
func (e OnboardingAccountSubtype) Valid() bool {
	switch e {
	case OnboardingAccountSubtypeBank:
		return true
	case OnboardingAccountSubtypeBrokerage:
		return true
	case OnboardingAccountSubtypeCash:
		return true
	case OnboardingAccountSubtypeLoan:
		return true
	case OnboardingAccountSubtypeMortgage:
		return true
	case OnboardingAccountSubtypeOther:
		return true
	case OnboardingAccountSubtypeRealEstate:
		return true
	case OnboardingAccountSubtypeSecurity:
		return true
	case OnboardingAccountSubtypeVehicle:
		return true
	default:
		return false
	}
}

// Defines values for ReconciliationMode.
const (
	AUTO    ReconciliationMode = "AUTO"
	CONFIRM ReconciliationMode = "CONFIRM"
)

// Valid indicates whether the value is a known member of the ReconciliationMode enum.
func (e ReconciliationMode) Valid() bool {
	switch e {
	case AUTO:
		return true
	case CONFIRM:
		return true
	default:
		return false
	}
}

// Defines values for TransactionStatus.
const (
	TransactionStatusPOSTED   TransactionStatus = "POSTED"
	TransactionStatusREPLACED TransactionStatus = "REPLACED"
	TransactionStatusREVERSAL TransactionStatus = "REVERSAL"
	TransactionStatusREVERSED TransactionStatus = "REVERSED"
)

// Valid indicates whether the value is a known member of the TransactionStatus enum.
func (e TransactionStatus) Valid() bool {
	switch e {
	case TransactionStatusPOSTED:
		return true
	case TransactionStatusREPLACED:
		return true
	case TransactionStatusREVERSAL:
		return true
	case TransactionStatusREVERSED:
		return true
	default:
		return false
	}
}

// Defines values for TransactionType.
const (
	TransactionTypeASSETPURCHASE  TransactionType = "ASSET_PURCHASE"
	TransactionTypeEXPENSE        TransactionType = "EXPENSE"
	TransactionTypeINCOME         TransactionType = "INCOME"
	TransactionTypeOPENINGBALANCE TransactionType = "OPENING_BALANCE"
	TransactionTypeREVERSAL       TransactionType = "REVERSAL"
	TransactionTypeTRANSFER       TransactionType = "TRANSFER"
)

// Valid indicates whether the value is a known member of the TransactionType enum.
func (e TransactionType) Valid() bool {
	switch e {
	case TransactionTypeASSETPURCHASE:
		return true
	case TransactionTypeEXPENSE:
		return true
	case TransactionTypeINCOME:
		return true
	case TransactionTypeOPENINGBALANCE:
		return true
	case TransactionTypeREVERSAL:
		return true
	case TransactionTypeTRANSFER:
		return true
	default:
		return false
	}
}

// Defines values for UserAccountClass.
const (
	UserAccountClassASSET     UserAccountClass = "ASSET"
	UserAccountClassLIABILITY UserAccountClass = "LIABILITY"
)

// Valid indicates whether the value is a known member of the UserAccountClass enum.
func (e UserAccountClass) Valid() bool {
	switch e {
	case UserAccountClassASSET:
		return true
	case UserAccountClassLIABILITY:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	AccountClass UserAccountClass   `json:"accountClass"`
	Archived     bool               `json:"archived"`
	Balance      DecimalAmount      `json:"balance"`
	Currency     Currency           `json:"currency"`
	HasPostings  bool               `json:"hasPostings"`
	Id           openapi_types.UUID `json:"id"`
	Name         string             `json:"name"`
	Subtype      AccountSubtype     `json:"subtype"`
}

// AccountListResponse defines model for AccountListResponse.
type AccountListResponse struct {
	Accounts []Account `json:"accounts"`
}

// AccountSubtype defines model for AccountSubtype.
type AccountSubtype string

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	User User `json:"user"`
}

// Category defines model for Category.
type Category struct {
	Archived  bool               `json:"archived"`
	Direction CategoryDirection  `json:"direction"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
}

// CategoryDirection defines model for CategoryDirection.
type CategoryDirection string

// CategoryListResponse defines model for CategoryListResponse.
type CategoryListResponse struct {
	Categories []Category `json:"categories"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string   `json:"currentPassword"`
	NewPassword     Password `json:"newPassword"`
}

// CompleteOnboardingRequest defines model for CompleteOnboardingRequest.
type CompleteOnboardingRequest struct {
	Account            OnboardingAccount          `json:"account"`
	DisplayCurrency    Currency                   `json:"displayCurrency"`
	FunctionalCurrency Currency                   `json:"functionalCurrency"`
	ReconciliationMode ReconciliationMode         `json:"reconciliationMode"`
	RecurringIncome    *OnboardingRecurringIncome `json:"recurringIncome,omitempty"`
	Timezone           string                     `json:"timezone"`
}

// CompleteOnboardingResponse defines model for CompleteOnboardingResponse.
type CompleteOnboardingResponse struct {
	AccountSetupId         openapi_types.UUID  `json:"accountSetupId"`
	RecurringIncomeSetupId *openapi_types.UUID `json:"recurringIncomeSetupId,omitempty"`
	User                   User                `json:"user"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	AccountClass       UserAccountClass    `json:"accountClass"`
	Currency           Currency            `json:"currency"`
	IdempotencyKey     *openapi_types.UUID `json:"idempotencyKey,omitempty"`
	Name               string              `json:"name"`
	OpeningBalance     *DecimalAmount      `json:"openingBalance,omitempty"`
	OpeningBalanceDate *openapi_types.Date `json:"openingBalanceDate,omitempty"`
	Subtype            AccountSubtype      `json:"subtype"`
}

// CreateCategoryRequest defines model for CreateCategoryRequest.
type CreateCategoryRequest struct {
	Direction CategoryDirection `json:"direction"`
	Name      string            `json:"name"`
}

// CreateTransactionRequest Typed operation contract. Raw journal entries are never accepted from clients.
type CreateTransactionRequest struct {
	// AccountId Required for opening balance, income, and expense.
	AccountId *openapi_types.UUID   `json:"accountId,omitempty"`
	Amount    PositiveDecimalAmount `json:"amount"`

	// CategoryId Required for income and expense.
	CategoryId  *openapi_types.UUID `json:"categoryId,omitempty"`
	Description *string             `json:"description,omitempty"`

	// DestinationAccountId Required for transfer and asset purchase.
	DestinationAccountId *openapi_types.UUID `json:"destinationAccountId,omitempty"`
	EventDate            openapi_types.Date  `json:"eventDate"`
	IdempotencyKey       openapi_types.UUID  `json:"idempotencyKey"`

	// SourceAccountId Required for transfer and asset purchase.
	SourceAccountId *openapi_types.UUID          `json:"sourceAccountId,omitempty"`
	Type            CreateTransactionRequestType `json:"type"`
}

// CreateTransactionRequestType defines model for CreateTransactionRequest.Type.
type CreateTransactionRequestType string

// Currency defines model for Currency.
type Currency string

// DecimalAmount defines model for DecimalAmount.
type DecimalAmount = string

// DeleteAccountRequest defines model for DeleteAccountRequest.
type DeleteAccountRequest struct {
	Password string `json:"password"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code    string             `json:"code"`
		Fields  *map[string]string `json:"fields,omitempty"`
		Message string             `json:"message"`
	} `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Service string               `json:"service"`
	Status  HealthResponseStatus `json:"status"`
	Version string               `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// LoginChallengeResponse defines model for LoginChallengeResponse.
type LoginChallengeResponse struct {
	ChallengeToken   string                       `json:"challengeToken"`
	ExpiresInSeconds int                          `json:"expiresInSeconds"`
	Status           LoginChallengeResponseStatus `json:"status"`
}

// LoginChallengeResponseStatus defines model for LoginChallengeResponse.Status.
type LoginChallengeResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// OnboardingAccount defines model for OnboardingAccount.
type OnboardingAccount struct {
	AccountClass       OnboardingAccountAccountClass `json:"accountClass"`
	Currency           Currency                      `json:"currency"`
	Name               string                        `json:"name"`
	OpeningBalance     DecimalAmount                 `json:"openingBalance"`
	OpeningBalanceDate openapi_types.Date            `json:"openingBalanceDate"`
	Subtype            OnboardingAccountSubtype      `json:"subtype"`
}

// OnboardingAccountAccountClass defines model for OnboardingAccount.AccountClass.
type OnboardingAccountAccountClass string

// OnboardingAccountSubtype defines model for OnboardingAccount.Subtype.
type OnboardingAccountSubtype string

// OnboardingRecurringIncome defines model for OnboardingRecurringIncome.
type OnboardingRecurringIncome struct {
	Amount     PositiveDecimalAmount `json:"amount"`
	Currency   Currency              `json:"currency"`
	DayOfMonth int                   `json:"dayOfMonth"`
	Name       string                `json:"name"`
}

// Password defines model for Password.
type Password = string

// PositiveDecimalAmount defines model for PositiveDecimalAmount.
type PositiveDecimalAmount = string

// ReconciliationMode defines model for ReconciliationMode.
type ReconciliationMode string

// RecoveryLoginRequest defines model for RecoveryLoginRequest.
type RecoveryLoginRequest struct {
	ChallengeToken string `json:"challengeToken"`
	RecoveryCode   string `json:"recoveryCode"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Password    Password            `json:"password"`
}

// ReplacementRequest defines model for ReplacementRequest.
type ReplacementRequest struct {
	// Operation Typed operation contract. Raw journal entries are never accepted from clients.
	Operation              CreateTransactionRequest `json:"operation"`
	ReversalIdempotencyKey openapi_types.UUID       `json:"reversalIdempotencyKey"`
}

// ReplacementResponse defines model for ReplacementResponse.
type ReplacementResponse struct {
	Replacement Transaction `json:"replacement"`
	Reversal    Transaction `json:"reversal"`
}

// ReversalRequest defines model for ReversalRequest.
type ReversalRequest struct {
	Description    *string            `json:"description,omitempty"`
	IdempotencyKey openapi_types.UUID `json:"idempotencyKey"`
}

// Session defines model for Session.
type Session struct {
	CreatedAt  time.Time          `json:"createdAt"`
	Current    bool               `json:"current"`
	ExpiresAt  time.Time          `json:"expiresAt"`
	Id         openapi_types.UUID `json:"id"`
	LastSeenAt time.Time          `json:"lastSeenAt"`
	UserAgent  *string            `json:"userAgent,omitempty"`
}

// SessionListResponse defines model for SessionListResponse.
type SessionListResponse struct {
	Sessions []Session `json:"sessions"`
}

// TOTPConfirmRequest defines model for TOTPConfirmRequest.
type TOTPConfirmRequest struct {
	Code string `json:"code"`
}

// TOTPConfirmResponse defines model for TOTPConfirmResponse.
type TOTPConfirmResponse struct {
	RecoveryCodes []string `json:"recoveryCodes"`
}

// TOTPDisableRequest defines model for TOTPDisableRequest.
type TOTPDisableRequest struct {
	Code     string `json:"code"`
	Password string `json:"password"`
}

// TOTPLoginRequest defines model for TOTPLoginRequest.
type TOTPLoginRequest struct {
	ChallengeToken string `json:"challengeToken"`
	Code           string `json:"code"`
}

// TOTPSetupResponse defines model for TOTPSetupResponse.
type TOTPSetupResponse struct {
	ProvisioningUri string `json:"provisioningUri"`
	Secret          string `json:"secret"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Amount                PositiveDecimalAmount `json:"amount"`
	CategoryId            *openapi_types.UUID   `json:"categoryId,omitempty"`
	CategoryName          *string               `json:"categoryName,omitempty"`
	CounterpartyAccountId *openapi_types.UUID   `json:"counterpartyAccountId,omitempty"`
	CounterpartyName      *string               `json:"counterpartyName,omitempty"`
	Currency              Currency              `json:"currency"`
	Description           *string               `json:"description,omitempty"`
	EventDate             openapi_types.Date    `json:"eventDate"`
	Id                    openapi_types.UUID    `json:"id"`
	PostedAt              time.Time             `json:"postedAt"`
	PrimaryAccountId      *openapi_types.UUID   `json:"primaryAccountId,omitempty"`
	PrimaryAccountName    string                `json:"primaryAccountName"`
	ReplacesTransactionId *openapi_types.UUID   `json:"replacesTransactionId,omitempty"`
	ReversesTransactionId *openapi_types.UUID   `json:"reversesTransactionId,omitempty"`
	Status                TransactionStatus     `json:"status"`
	Type                  TransactionType       `json:"type"`
}

// TransactionStatus defines model for Transaction.Status.
type TransactionStatus string

// TransactionListResponse defines model for TransactionListResponse.
type TransactionListResponse struct {
	NextCursor   *string       `json:"nextCursor,omitempty"`
	Transactions []Transaction `json:"transactions"`
}

// TransactionType defines model for TransactionType.
type TransactionType string

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	Archived *bool     `json:"archived,omitempty"`
	Currency *Currency `json:"currency,omitempty"`
	Name     *string   `json:"name,omitempty"`
}

// UpdateCategoryRequest defines model for UpdateCategoryRequest.
type UpdateCategoryRequest struct {
	Archived *bool   `json:"archived,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	CurrentPassword *string             `json:"currentPassword,omitempty"`
	DisplayName     string              `json:"displayName"`
	Email           openapi_types.Email `json:"email"`
}

// UpdateUserSettingsRequest defines model for UpdateUserSettingsRequest.
type UpdateUserSettingsRequest struct {
	DisplayCurrency    Currency           `json:"displayCurrency"`
	FunctionalCurrency Currency           `json:"functionalCurrency"`
	ReconciliationMode ReconciliationMode `json:"reconciliationMode"`
	Timezone           string             `json:"timezone"`
}

// User defines model for User.
type User struct {
	DisplayCurrency     Currency            `json:"displayCurrency"`
	DisplayName         string              `json:"displayName"`
	Email               openapi_types.Email `json:"email"`
	FunctionalCurrency  Currency            `json:"functionalCurrency"`
	Id                  openapi_types.UUID  `json:"id"`
	OnboardingCompleted bool                `json:"onboardingCompleted"`
	ReconciliationMode  ReconciliationMode  `json:"reconciliationMode"`
	Timezone            string              `json:"timezone"`
	TotpEnabled         bool                `json:"totpEnabled"`
}

// UserAccountClass defines model for UserAccountClass.
type UserAccountClass string

// AccountId defines model for AccountId.
type AccountId = openapi_types.UUID

// CategoryId defines model for CategoryId.
type CategoryId = openapi_types.UUID

// TransactionId defines model for TransactionId.
type TransactionId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// Conflict defines model for Conflict.
type Conflict = ErrorEnvelope

// InternalError defines model for InternalError.
type InternalError = ErrorEnvelope

// NotFound defines model for NotFound.
type NotFound = ErrorEnvelope

// RateLimited defines model for RateLimited.
type RateLimited = ErrorEnvelope

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorEnvelope

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// ListAccountsParams defines parameters for ListAccounts.
type ListAccountsParams struct {
	IncludeArchived *bool `form:"includeArchived,omitempty" json:"includeArchived,omitempty"`
}

// ListCategoriesParams defines parameters for ListCategories.
type ListCategoriesParams struct {
	IncludeArchived *bool `form:"includeArchived,omitempty" json:"includeArchived,omitempty"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	From       *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To         *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
	AccountId  *openapi_types.UUID `form:"accountId,omitempty" json:"accountId,omitempty"`
	CategoryId *openapi_types.UUID `form:"categoryId,omitempty" json:"categoryId,omitempty"`
	Type       *TransactionType    `form:"type,omitempty" json:"type,omitempty"`
	Cursor     *string             `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit      *int                `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// VerifyLoginRecoveryCodeJSONRequestBody defines body for VerifyLoginRecoveryCode for application/json ContentType.
type VerifyLoginRecoveryCodeJSONRequestBody = RecoveryLoginRequest

// VerifyLoginTOTPJSONRequestBody defines body for VerifyLoginTOTP for application/json ContentType.
type VerifyLoginTOTPJSONRequestBody = TOTPLoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ConfirmTOTPJSONRequestBody defines body for ConfirmTOTP for application/json ContentType.
type ConfirmTOTPJSONRequestBody = TOTPConfirmRequest

// DisableTOTPJSONRequestBody defines body for DisableTOTP for application/json ContentType.
type DisableTOTPJSONRequestBody = TOTPDisableRequest

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CreateCategoryRequest

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody = UpdateCategoryRequest

// CompleteOnboardingJSONRequestBody defines body for CompleteOnboarding for application/json ContentType.
type CompleteOnboardingJSONRequestBody = CompleteOnboardingRequest

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = CreateTransactionRequest

// ReplaceTransactionJSONRequestBody defines body for ReplaceTransaction for application/json ContentType.
type ReplaceTransactionJSONRequestBody = ReplacementRequest

// ReverseTransactionJSONRequestBody defines body for ReverseTransaction for application/json ContentType.
type ReverseTransactionJSONRequestBody = ReversalRequest

// DeleteAccountJSONRequestBody defines body for DeleteAccount for application/json ContentType.
type DeleteAccountJSONRequestBody = DeleteAccountRequest

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = UpdateProfileRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// UpdateUserSettingsJSONRequestBody defines body for UpdateUserSettings for application/json ContentType.
type UpdateUserSettingsJSONRequestBody = UpdateUserSettingsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAccounts List owned user accounts with exact ledger balances
	// (GET /api/v1/accounts)
	ListAccounts(w http.ResponseWriter, r *http.Request, params ListAccountsParams)
	// CreateAccount Create an account and optionally post its opening balance atomically
	// (POST /api/v1/accounts)
	CreateAccount(w http.ResponseWriter, r *http.Request)
	// UpdateAccount Rename, archive, restore, or change an unused account currency
	// (PATCH /api/v1/accounts/{accountId})
	UpdateAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Login Authenticate with email and password
	// (POST /api/v1/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// VerifyLoginRecoveryCode Complete a password login with a one-time recovery code
	// (POST /api/v1/auth/login/recovery)
	VerifyLoginRecoveryCode(w http.ResponseWriter, r *http.Request)
	// VerifyLoginTOTP Complete a password login with an authenticator code
	// (POST /api/v1/auth/login/totp)
	VerifyLoginTOTP(w http.ResponseWriter, r *http.Request)
	// Logout Revoke the current browser session
	// (POST /api/v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// GetCurrentUser Return the current authenticated user
	// (GET /api/v1/auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Register Register an identity and create its first browser session
	// (POST /api/v1/auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// ListSessions List active sessions for the current user
	// (GET /api/v1/auth/sessions)
	ListSessions(w http.ResponseWriter, r *http.Request)
	// RevokeSession Revoke one active session owned by the current user
	// (DELETE /api/v1/auth/sessions/{sessionId})
	RevokeSession(w http.ResponseWriter, r *http.Request, sessionId openapi_types.UUID)
	// ConfirmTOTP Confirm pending TOTP and issue one-time recovery codes
	// (POST /api/v1/auth/totp/confirm)
	ConfirmTOTP(w http.ResponseWriter, r *http.Request)
	// DisableTOTP Disable TOTP after password and authenticator verification
	// (POST /api/v1/auth/totp/disable)
	DisableTOTP(w http.ResponseWriter, r *http.Request)
	// SetupTOTP Generate an encrypted pending TOTP credential
	// (POST /api/v1/auth/totp/setup)
	SetupTOTP(w http.ResponseWriter, r *http.Request)
	// ListCategories List owned income and expense categories
	// (GET /api/v1/categories)
	ListCategories(w http.ResponseWriter, r *http.Request, params ListCategoriesParams)
	// CreateCategory Create a category and its private ledger account atomically
	// (POST /api/v1/categories)
	CreateCategory(w http.ResponseWriter, r *http.Request)
	// UpdateCategory Rename, archive, or restore an owned category
	// (PATCH /api/v1/categories/{categoryId})
	UpdateCategory(w http.ResponseWriter, r *http.Request, categoryId CategoryId)
	// GetLiveness Confirm that the API process is running
	// (GET /api/v1/health/live)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// GetReadiness Confirm that the API can serve database-backed requests
	// (GET /api/v1/health/ready)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// CompleteOnboarding Save settings, first account, opening balance, and optional recurring income atomically
	// (POST /api/v1/onboarding/complete)
	CompleteOnboarding(w http.ResponseWriter, r *http.Request)
	// ListTransactions List immutable operations using stable cursor pagination
	// (GET /api/v1/transactions)
	ListTransactions(w http.ResponseWriter, r *http.Request, params ListTransactionsParams)
	// CreateTransaction Post one typed financial operation as a balanced transaction
	// (POST /api/v1/transactions)
	CreateTransaction(w http.ResponseWriter, r *http.Request)
	// ReplaceTransaction Atomically reverse an operation and post its corrected replacement
	// (POST /api/v1/transactions/{transactionId}/replacement)
	ReplaceTransaction(w http.ResponseWriter, r *http.Request, transactionId TransactionId)
	// ReverseTransaction Preserve and reverse an owned posted transaction
	// (POST /api/v1/transactions/{transactionId}/reversal)
	ReverseTransaction(w http.ResponseWriter, r *http.Request, transactionId TransactionId)
	// DeleteAccount Permanently delete the user and all owned data after password confirmation
	// (DELETE /api/v1/users/me)
	DeleteAccount(w http.ResponseWriter, r *http.Request)
	// UpdateProfile Update display name or email with password confirmation for email changes
	// (PATCH /api/v1/users/me)
	UpdateProfile(w http.ResponseWriter, r *http.Request)
	// ChangePassword Change password and revoke all other sessions
	// (PUT /api/v1/users/me/password)
	ChangePassword(w http.ResponseWriter, r *http.Request)
	// UpdateUserSettings Update timezone, currencies, and reconciliation preference
	// (PATCH /api/v1/users/me/settings)
	UpdateUserSettings(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListAccounts List owned user accounts with exact ledger balances
// (GET /api/v1/accounts)
func (_ Unimplemented) ListAccounts(w http.ResponseWriter, r *http.Request, params ListAccountsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateAccount Create an account and optionally post its opening balance atomically
// (POST /api/v1/accounts)
func (_ Unimplemented) CreateAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateAccount Rename, archive, restore, or change an unused account currency
// (PATCH /api/v1/accounts/{accountId})
func (_ Unimplemented) UpdateAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login Authenticate with email and password
// (POST /api/v1/auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// VerifyLoginRecoveryCode Complete a password login with a one-time recovery code
// (POST /api/v1/auth/login/recovery)
func (_ Unimplemented) VerifyLoginRecoveryCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// VerifyLoginTOTP Complete a password login with an authenticator code
// (POST /api/v1/auth/login/totp)
func (_ Unimplemented) VerifyLoginTOTP(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Revoke the current browser session
// (POST /api/v1/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCurrentUser Return the current authenticated user
// (GET /api/v1/auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register Register an identity and create its first browser session
// (POST /api/v1/auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListSessions List active sessions for the current user
// (GET /api/v1/auth/sessions)
func (_ Unimplemented) ListSessions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RevokeSession Revoke one active session owned by the current user
// (DELETE /api/v1/auth/sessions/{sessionId})
func (_ Unimplemented) RevokeSession(w http.ResponseWriter, r *http.Request, sessionId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ConfirmTOTP Confirm pending TOTP and issue one-time recovery codes
// (POST /api/v1/auth/totp/confirm)
func (_ Unimplemented) ConfirmTOTP(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DisableTOTP Disable TOTP after password and authenticator verification
// (POST /api/v1/auth/totp/disable)
func (_ Unimplemented) DisableTOTP(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SetupTOTP Generate an encrypted pending TOTP credential
// (POST /api/v1/auth/totp/setup)
func (_ Unimplemented) SetupTOTP(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListCategories List owned income and expense categories
// (GET /api/v1/categories)
func (_ Unimplemented) ListCategories(w http.ResponseWriter, r *http.Request, params ListCategoriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateCategory Create a category and its private ledger account atomically
// (POST /api/v1/categories)
func (_ Unimplemented) CreateCategory(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateCategory Rename, archive, or restore an owned category
// (PATCH /api/v1/categories/{categoryId})
func (_ Unimplemented) UpdateCategory(w http.ResponseWriter, r *http.Request, categoryId CategoryId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetLiveness Confirm that the API process is running
// (GET /api/v1/health/live)
func (_ Unimplemented) GetLiveness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReadiness Confirm that the API can serve database-backed requests
// (GET /api/v1/health/ready)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CompleteOnboarding Save settings, first account, opening balance, and optional recurring income atomically
// (POST /api/v1/onboarding/complete)
func (_ Unimplemented) CompleteOnboarding(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListTransactions List immutable operations using stable cursor pagination
// (GET /api/v1/transactions)
func (_ Unimplemented) ListTransactions(w http.ResponseWriter, r *http.Request, params ListTransactionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateTransaction Post one typed financial operation as a balanced transaction
// (POST /api/v1/transactions)
func (_ Unimplemented) CreateTransaction(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ReplaceTransaction Atomically reverse an operation and post its corrected replacement
// (POST /api/v1/transactions/{transactionId}/replacement)
func (_ Unimplemented) ReplaceTransaction(w http.ResponseWriter, r *http.Request, transactionId TransactionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ReverseTransaction Preserve and reverse an owned posted transaction
// (POST /api/v1/transactions/{transactionId}/reversal)
func (_ Unimplemented) ReverseTransaction(w http.ResponseWriter, r *http.Request, transactionId TransactionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteAccount Permanently delete the user and all owned data after password confirmation
// (DELETE /api/v1/users/me)
func (_ Unimplemented) DeleteAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateProfile Update display name or email with password confirmation for email changes
// (PATCH /api/v1/users/me)
func (_ Unimplemented) UpdateProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ChangePassword Change password and revoke all other sessions
// (PUT /api/v1/users/me/password)
func (_ Unimplemented) ChangePassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateUserSettings Update timezone, currencies, and reconciliation preference
// (PATCH /api/v1/users/me/settings)
func (_ Unimplemented) UpdateUserSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAccountsParams

	// ------------- Optional query parameter "includeArchived" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "includeArchived", r.URL.Query(), &params.IncludeArchived, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "includeArchived"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "includeArchived", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccounts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAccount operation middleware
func (siw *ServerInterfaceWrapper) UpdateAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyLoginRecoveryCode operation middleware
func (siw *ServerInterfaceWrapper) VerifyLoginRecoveryCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyLoginRecoveryCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyLoginTOTP operation middleware
func (siw *ServerInterfaceWrapper) VerifyLoginTOTP(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyLoginTOTP(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeSession operation middleware
func (siw *ServerInterfaceWrapper) RevokeSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmTOTP operation middleware
func (siw *ServerInterfaceWrapper) ConfirmTOTP(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmTOTP(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DisableTOTP operation middleware
func (siw *ServerInterfaceWrapper) DisableTOTP(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DisableTOTP(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetupTOTP operation middleware
func (siw *ServerInterfaceWrapper) SetupTOTP(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetupTOTP(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCategoriesParams

	// ------------- Optional query parameter "includeArchived" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "includeArchived", r.URL.Query(), &params.IncludeArchived, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "includeArchived"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "includeArchived", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCategories(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCategory operation middleware
func (siw *ServerInterfaceWrapper) CreateCategory(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCategory(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCategory operation middleware
func (siw *ServerInterfaceWrapper) UpdateCategory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "categoryId" -------------
	var categoryId CategoryId

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", chi.URLParam(r, "categoryId"), &categoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "categoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCategory(w, r, categoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteOnboarding operation middleware
func (siw *ServerInterfaceWrapper) CompleteOnboarding(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteOnboarding(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListTransactions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTransactionsParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "accountId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "accountId", r.URL.Query(), &params.AccountId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "accountId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "categoryId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "categoryId", r.URL.Query(), &params.CategoryId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "categoryId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "categoryId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTransactions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTransaction operation middleware
func (siw *ServerInterfaceWrapper) CreateTransaction(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTransaction(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceTransaction operation middleware
func (siw *ServerInterfaceWrapper) ReplaceTransaction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "transactionId" -------------
	var transactionId TransactionId

	err = runtime.BindStyledParameterWithOptions("simple", "transactionId", chi.URLParam(r, "transactionId"), &transactionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transactionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceTransaction(w, r, transactionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReverseTransaction operation middleware
func (siw *ServerInterfaceWrapper) ReverseTransaction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "transactionId" -------------
	var transactionId TransactionId

	err = runtime.BindStyledParameterWithOptions("simple", "transactionId", chi.URLParam(r, "transactionId"), &transactionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transactionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReverseTransaction(w, r, transactionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAccount operation middleware
func (siw *ServerInterfaceWrapper) DeleteAccount(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateProfile(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUserSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateUserSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUserSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/health/live", wrapper.GetLiveness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/health/ready", wrapper.GetReadiness)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login/totp", wrapper.VerifyLoginTOTP)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login/recovery", wrapper.VerifyLoginRecoveryCode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/sessions", wrapper.ListSessions)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/auth/sessions/{sessionId}", wrapper.RevokeSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/totp/setup", wrapper.SetupTOTP)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/totp/confirm", wrapper.ConfirmTOTP)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/totp/disable", wrapper.DisableTOTP)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/users/me", wrapper.DeleteAccount)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/users/me", wrapper.UpdateProfile)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/users/me/password", wrapper.ChangePassword)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/users/me/settings", wrapper.UpdateUserSettings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/onboarding/complete", wrapper.CompleteOnboarding)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/accounts", wrapper.ListAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/accounts", wrapper.CreateAccount)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/accounts/{accountId}", wrapper.UpdateAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/categories", wrapper.ListCategories)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/categories", wrapper.CreateCategory)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/categories/{categoryId}", wrapper.UpdateCategory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/transactions", wrapper.ListTransactions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/transactions", wrapper.CreateTransaction)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/transactions/{transactionId}/reversal", wrapper.ReverseTransaction)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/transactions/{transactionId}/replacement", wrapper.ReplaceTransaction)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5H1Zc9s4tvBfQeHrh5mvmEh2d091+2VKXpL4xrFVkj1L9+R2weSRhA4JsAFQjsZX//0WAK4iKFHUEnvu",
	"S0qWsJwNZwfyjH0exZwBUxKfPeOYCBKBAmH+Gvg+T5i6DvQflOEzHBM1wx5mJAJ8hkn+u4cF/JFQAQE+",
	"UyIBD0t/BhHREydcREThM5wkVI9Ui1hPlkpQNsXLpYcviIIpF4vGjfxiwG473QvCJPEV5axxM1UZs8t+",
	"Sz1ZxpxJMPQ8J8EI/khAKv2Xz5kCZj6SOA6pT/SWvd8lZ/q7YpvvBEzwGf5/vYJXPfur7F0JwcUVm0PI",
	"Y7BbBiB9QWO9GD7D6YZoTkIamB3QhNAQAqwJz9kkpP5RwZE8ET4gqYgC5KcASPRE1QypGSCRUmjp4Wum",
	"QDASmlWPB2O2LZIg5iAQmO2XHr7l6h1PWHA8UO6eGARIZER7IhIxrtDEQLH08IgouKERVXBEoO45RxFh",
	"C0SUgihWEnt4BiRItcYIlFi8GUwUiOqm6fGgTMEUhF556eExiDn14YGROaEheQzhuGdDn2wUQAwsAOYv",
	"UFICZOnhB0YSNeOC/vuYFB4kagZMpasjLpAvINDfkBDNQdBJ9lN2lpeZXiorbgNlEFA9koRDwWMQimpd",
	"NCGhBA/Hpa+eM3V+ERIpN6HwIEEMyuOXHibCn9G5pVPK60fOQyBM//pIQsJ82LTwJfg0IuEgMggsPewn",
	"QmjObJp4kY1benhG5JBLRdlUuoGhQQv9nVmE5/oPMnm0362HKaXQOB1tDUJmTX7FZlOzh1clfrFBCf+C",
	"hCVSV3H9nOPAH38H39AvheGGSjVKjVE3uTCfqYJItkRb756CQ4Qgixr++cJr4B4XlAaWRHraI2FfNGGI",
	"1Fb7UfAvIMgUjKkm4W9gTAv28Bxm1A/1Jwl+IqjSNIy4UFM7OuSEYQ9zNQNRAqHgsj6GHWmWSKv9Np2h",
	"Gk3MRBc9MidpW+atPZQBFeBbpbPhdKW7X+YTdj5Faw5DAVZJ1NcR5bKMRyYn17cXd5+usIev/jG8uh1f",
	"OXmcrbDD+Ui90/SvVickZ+amI1Ja24n/jLApDImUT1yUncttwDcKRmWL6K8i8vUG2FTN8NnJ6U8ejijL",
	"/v7JxWB4Ks9eh3g+roboChTVVZ248ygOQcEde+REBJRNu+FPCmO5DvJim5J6C6iMQ7K46GCjJgnzLYRd",
	"ZgvwOfNpSI0b8IkHG23RqD7DrpMIzcdr5vMI2hNhtDJRCzKN4N+cwaoE9fsVCTrxNmiCfB0nkepEd1Ij",
	"t6itZWcX2zgGlcTX7dThCsm3mbqbVfFWoXVSRgBRkIr4Tgeqsx/ZxeOjAUQxV/rPj7DYyixtJaoe5jEw",
	"yqbnHd3Z6vRL7amUgQ2s63Igh7O1r9ksGZnl6iYau/kbnTjmJkEBSDOqpWRRW2xXAuVFDAHSg2ywpoNH",
	"QXz1Fo3IE/qdJybLAExp+46IAMRgDgIR34dYQYAmgkfID6kmzVvccM6s7miIbCdcoFTkUBo+eIgaxeMh",
	"wgIEX2NgEvTqG08MidoYyiGXVNE51CO5SppvDcAWvq3Bq6xYkZIfW5zrAHQQZRg1aElYkymcaIaxABEp",
	"QaE4Ef6MtAQY5sBUaxXQQcXZtNGx0FmN0+6GV7fXt+9/Ox/cDG4vtCNe88g9fD8a3I7fXY2whwfj8dX9",
	"b8OH0cWHgdNbX/UTrNIqqJhLaI1YzkNeMjMZyA/jSw3dgwbnv4b/xB5+fz7EHr641Z8HD/rXi4H598M7",
	"7OEPH/Xn8Xvz79VH7OGPo79jD9/e6c+3v1wapPVqn/5xq7H9u/7ml4H+5nx0gz18+VGPfBh80HN/ucce",
	"Hj2c672uLp3xSvVUmZS9UiA0M//7zV//1P+fX0/e/Pz51/6bnz///z//6V//ems+Pp94Py3//NfvsHNF",
	"7QntZPHjrrHDCkfjdf5+NWu2HYCQZZC3iYtSp7pGsAmFMJDNqz03HY0SMhFISaYtwmLfOrPZ+DphVsZb",
	"TF30+wAk7JzPkDZN606GKaKSlGRMyw7mX1yCNgchU928Hud0QS/ftZjrQuyGTym7mJEwBDaFrkF8Nv+e",
	"fwHmxBO+xlSAvGZjHW5YCYgoo5HWHYVJyfPbLsooruLfcly9toRYgc4BSyNhup1oiAgNKzbGfuOVz/f3",
	"p30Hm/elDLIN1yqFelS+W6ySGQJji7CHb64H59c31/f/dCrjLpHKaw07jpx97Rq51CjlxH29KI3qSZFt",
	"RGpHL7mDTAVkcTf5xJkWHiNZVielJ26NgtpjRJW7XiVWlOByUbxlyvHk1CGZbvpV/aEu3tDImVjL1cLD",
	"/Z12/u5u312PPjl1gl5gDmKxg/Kt26I1/Pmh784xGSAuUvgrSrtK3L9s4m/N9lQWd/F1BFMqFYiuOQKT",
	"3rvtpif3ZLg65bCzncoYbLBfI4hD4kMEXV3vPLuwUV805TQMEtq/IuH1tiHmCgEa1vFKUG4kQifvTRQr",
	"bKJDiQJl1Lea1oC2ORsFIG5U7dCOR2OnDAfdkbstYuoxyMzF30bfGdEMBqrmk7xRNHI6Jmm5yF3VTJ3j",
	"bdZrWcoMiVRjALbN0okEMZhWgV1XAy2oUdmvjFaB/xom7FDRlHaF9vXMjO+bypn5wi647+/uhxecTaiI",
	"OtrN1NqVXABr7/+y/G6jdPtN1qwCVkftVBjMKk1rwhKRr9f2xxN7oEt/raVsdY8mPC6pJI8hHIO83v6z",
	"Qt56Jn1Tj2s32Vt1sdbiacp3HUUxFnxO9RGkbPogaFXpCeqMAcEX0EJ5peO82h5OPErm9LjhVaUIsVHh",
	"Z8NvmzrBTDwKIiZCLSqJ9s1Ll2Y2L98lGqx6CTuXHVphE3O5pQmPBY2I2JJo1UmNZEvdMFnr925RndcO",
	"WpeZRbIvixaHd+P7q0vs4dHV365G49LHwY35OLwZXDTk+dtUe0sw3jf2F66rkpRCdQdhvSL/mHN3w1ne",
	"wedg8FVdJELaPH2dHsUm7d2SFV9/rQGtbLABzfv9VrpKUuEShYc42LklY20X4NHSmK5KiMVut7aC9ejt",
	"GdSh4BPa2Yfa3GxXr0x/m4RIi+TG50YiPUgQY1CmLXmnNNDrba17Ue1wTk6l3WTHYcqKFG8hp/UC7E78",
	"benQ8LwckDULNqiXQ8hL3fxxFV8xHbs5oXAZfnc2ck/NlS7qVKFskrjBDhU3jSdlE+5oZLka3+f9Vbab",
	"ZQbo0+IdZYT5gGIQUmP6ZpJ+8QSPqHSD560hjQr1bsWswfC6VHs+w/23p2/7WTmNxBSf4e/fnrztmyyv",
	"mhl8eiSmvflJr3xrYmrjpzwLqj1KrH2lQTbIq1y9/DW9mPhHAmJR3EykzA+TAAbF5Y/ivlEAE5KEKj+3",
	"NQn5vHIZ8bTf39uFJtcdk8bbbDlhlh7+oX/StHYObK9yB8vcdEoi7aumNETcLJtI2zln1rbXCeGrFoYQ",
	"gimIrPtNk1qRqSYyviByNgn5E/6cBjB1JlXaYdPLoCDVOQ8We6Oes+V2WT3TSiSwrHHwZN8cdF5Gsz+h",
	"NC9p2dbfzLbSbddunNaTft48Kb/EWhUNS1VEWCYUpq2Nx1bjhQukGY6okqv9kYgoHlFfj3HLytKrHfLe",
	"c96MuUyzQP6sLk0VT75+5l14FkN6RaRsD/P+JdEZabSSxP4xJTExYB5ZEn/YPCm/H7yj6I5AK3wPpWGN",
	"hwRIxQV45iaoufKj5TphiSz0KSoF8xuENlGzXsin1HDFrfdMLvVA+q6Spz22dJWv9DlELC1kZMoOPYJP",
	"Egno/u5+iKhEgU2gGxaf9k/3S5N6D5sDwix0LLrETbsu4sym2iyoeUbZ3Bn/Fqr7tIX8l6+vLz38YxvY",
	"qo8CmFnfb57luGZePXOlK9eQeg/afzbELRUgspNVvaHddL56WVWm+aD9DQSdZM0ipb6Kwxw9Z3PKCzuC",
	"GYzI54F5IUImUSrlsno6X7Y8V72RNEpCJJcmZETEylrp+Ioy+ttLnA7BWkmbVhMHkrJaMe6FSViJlNqg",
	"ajGrKNP/XDFjiNRw31LGeKLWug369xpvf6hH7OeCP+mQLSO2gDn/AoF2cUgogAQLRB4l2KpdF8uw4lLp",
	"1U1SIE3BoscqANuQwaawnFH9e1A2d6Ie7J3LlyDlaXjcWSq/pWEegUoEq3CO1DHbgnki7U5sluKsf/Fg",
	"RrjaHnnsUH+D3Fybh2bUYq+qcKtg6Hje44qkWb5oNUnLRLDIm1zBhAq5k+oot1Y1pgXH2aADqg9Xl5gz",
	"5lZ0DigHe19JO1JdN0/ZZmd821OdLdR7Tj+lmZjA3G5znXFtEMY5A13p1+q7cPm6O70J97mNbRxXbeKx",
	"shYui8kZrPAqzbc+Lnbil/ZTe75tq2vWxGnf3YF91ZWmwyN7q67+QterazqsB1tcMVqpEihIJIyd1A4U",
	"8+HVJGkt3igGFlA2tbkLjRyVMoGGoEhuLWdp1qZZztK+yAPL2Ur3ZSs5c2iHnEg1CYj4/JjhSoWVKXIp",
	"CyfajuYhiMlQVQKP8iN2W7NTgkrWBLmmPzJn5YG8qHojpitXVxbr0hN+FW9qN7K/B6ZxNwlhYL5YmCg2",
	"dm/cktLVB60avZSLYtjrLl863wBrrF+WqLPfCmb92YvyXh3KlvkrY4esW652bh05mileUqvzK/vttZYu",
	"M/bbKESHH7Ggc/1TWtPOK5vtK5aFRPWei17ozUXLkixtV7UsPe582LJlJ0HsH1cQ/89VLrnIipfaQPGy",
	"At0sqzPzYkUvpPO1+bYbOgcG8qDR8srjGa5AeXiNYsF9kBJRiYiB2u3tqhlRJnhamSMSxnSUWNDFbuuk",
	"ikmRriPLCEhAXwZdtPoKiCKPRIJ558oCv7ccoZOwPmH2Be986zePxP9i3tM2R0puIHTR42bAyvIITZHq",
	"6ouCh7K6jc9eHlvhNb+h6PKd8lHIzzsGX4k9HhOT/bDdzF6aA0xtr1d/Xq3cZ4Ty1x5z985lq0tSUxHB",
	"1VsPjb74fXlgK298IniEnZkr902gpedeR/F9rFL+ryS2+A8d3ItV/ruInVdLL9C0DAvrV3IaYLRXXcrr",
	"lprET/v91vCFNKLKHUyd/ugVr4FkjeeNz4EcNMZquiTkKkBEUaJMLqF4OjEmU/hGiQ0TodE6TBIlUp9r",
	"ab+3DNWApq8IdonYyheWDhm0uZ6BOG7cVn1PoW4uCs6bq2evxVQMuQ7nGSBl3v603eaUhCVRJhKRzFgE",
	"SFU4vt4fLluD3nPl/6lZ9laewGiqbJpBVTHbLp6rXow8VEjneBflyALqepTEJaiC6gOvDb25OGqTnT4X",
	"AnxVef31WwjyEUO/Qe7XZKQwEV8h9iwoWq4L+pTFdkf5Lx5yaRJ+A9ZrEP7qIzEvSzVn0P2nC/RQgA0f",
	"bamlEGmTxLDIb6W+E6lFyPYONZWlK4+xHsgFcD742rUY9SDTB4MtWXSojSxy36oQNQQRET0+XKSQmJRA",
	"kgFKwrAM7EqpKi1Jr3pwGk1p3bd1WdL0bjA+ZJ5z5f7xC+uttDAGKE4p8Ur8Ngs2Sm8/Ih1aIS7SHnDT",
	"O+mUENO2YgfZexnSITMOFdArv40TJ654oPI/uxwqGHD+9zFdVUF+M8GSwnpC5n3Pos2n0tFydNVg8a3W",
	"pS1EVitUYG3JySwvtLGCUr4Sf1AF4bp7/0K1RE68byMP6anP7kR72R0qCtLLOyyKu88oFjABPQBcwrG0",
	"D1ZnrmQiQnyWyQtefl7+bwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
