/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Confirm that the API process is running */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Confirm that the API can serve database-backed requests */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return converted wealth and cashflow dashboard data */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register an identity and create its first browser session */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a password login with an authenticator code */
        post: operations["verifyLoginTOTP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a password login with a one-time recovery code */
        post: operations["verifyLoginRecoveryCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current browser session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active sessions for the current user */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one active session owned by the current user */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate an encrypted pending TOTP credential */
        post: operations["setupTOTP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm pending TOTP and issue one-time recovery codes */
        post: operations["confirmTOTP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable TOTP after password and authenticator verification */
        post: operations["disableTOTP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Permanently delete the user and all owned data after password confirmation */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        /** Update display name or email with password confirmation for email changes */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change password and revoke all other sessions */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update timezone, currencies, and reconciliation preference */
        patch: operations["updateUserSettings"];
        trace?: never;
    };
    "/api/v1/onboarding/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save settings, first account, opening balance, and optional recurring income atomically */
        post: operations["completeOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List owned user accounts with exact ledger balances */
        get: operations["listAccounts"];
        put?: never;
        /** Create an account and optionally post its opening balance atomically */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename, archive, restore, or change an unused account currency */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List owned income and expense categories */
        get: operations["listCategories"];
        put?: never;
        /** Create a category and its private ledger account atomically */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename, archive, or restore an owned category */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List immutable operations using stable cursor pagination */
        get: operations["listTransactions"];
        put?: never;
        /** Post one typed financial operation as a balanced transaction */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{transactionId}/reversal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preserve and reverse an owned posted transaction */
        post: operations["reverseTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{transactionId}/replacement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically reverse an operation and post its corrected replacement */
        post: operations["replaceTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurring-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List owned recurring operation templates */
        get: operations["listRecurringTemplates"];
        put?: never;
        /** Create a typed recurring operation template */
        post: operations["createRecurringTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurring-templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit, pause, resume, archive, or restore a recurring template */
        patch: operations["updateRecurringTemplate"];
        trace?: never;
    };
    "/api/v1/reconciliation/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the reminder window and per-account completion for one month */
        get: operations["getReconciliationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconciliation/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview in CONFIRM mode or atomically apply in AUTO mode */
        post: operations["prepareReconciliation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconciliation/previews/{previewId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revalidate a reconciliation preview and apply it atomically */
        post: operations["confirmReconciliation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List manual asset profiles and their current owned values */
        get: operations["listAssets"];
        put?: never;
        /** Create a manual asset profile and optionally post its purchase atomically */
        post: operations["createAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return one owned manual asset profile */
        get: operations["getAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update, archive, or restore a manual asset profile */
        patch: operations["updateAsset"];
        trace?: never;
    };
    "/api/v1/assets/{assetId}/valuations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List immutable manual valuation snapshots for one asset */
        get: operations["listAssetValuations"];
        put?: never;
        /** Record a manual valuation and post its idempotent revaluation delta */
        post: operations["createAssetValuation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DashboardResponse: {
            currency: components["schemas"]["Currency"];
            month: string;
            fxStatus: components["schemas"]["DashboardFXStatus"];
            netWorth: components["schemas"]["DecimalAmount"];
            assets: components["schemas"]["DecimalAmount"];
            liabilities: components["schemas"]["DecimalAmount"];
            cash: components["schemas"]["DecimalAmount"];
            monthlyIncome: components["schemas"]["DecimalAmount"];
            monthlyExpenses: components["schemas"]["DecimalAmount"];
            netSavings: components["schemas"]["DecimalAmount"];
            /** @description Exact percent decimal, null when monthly income is zero. */
            savingsRate: string | null;
            netWorthHistory: components["schemas"]["DashboardNetWorthPoint"][];
            cashflowHistory: components["schemas"]["DashboardCashflowPoint"][];
            assetAllocation: components["schemas"]["DashboardBreakdown"][];
            currencyExposure: components["schemas"]["DashboardBreakdown"][];
        };
        DashboardFXStatus: {
            /** @enum {string} */
            state: "COMPLETE" | "STALE" | "INCOMPLETE";
            missingCurrencies: components["schemas"]["Currency"][];
            staleCurrencies: components["schemas"]["Currency"][];
        };
        DashboardNetWorthPoint: {
            month: string;
            netWorth: components["schemas"]["DecimalAmount"];
        };
        DashboardCashflowPoint: {
            month: string;
            income: components["schemas"]["DecimalAmount"];
            expenses: components["schemas"]["DecimalAmount"];
            savings: components["schemas"]["DecimalAmount"];
        };
        DashboardBreakdown: {
            label: string;
            value: components["schemas"]["DecimalAmount"];
        };
        HealthResponse: {
            /** @constant */
            status: "ok";
            service: string;
            version: string;
        };
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                fields?: {
                    [key: string]: string;
                };
            };
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            displayName: string;
            password: components["schemas"]["Password"];
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TOTPLoginRequest: {
            challengeToken: string;
            code: string;
        };
        RecoveryLoginRequest: {
            challengeToken: string;
            recoveryCode: string;
        };
        LoginChallengeResponse: {
            /** @constant */
            status: "totp_required";
            challengeToken: string;
            expiresInSeconds: number;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            timezone: string;
            functionalCurrency: components["schemas"]["Currency"];
            displayCurrency: components["schemas"]["Currency"];
            reconciliationMode: components["schemas"]["ReconciliationMode"];
            onboardingCompleted: boolean;
            totpEnabled: boolean;
        };
        SessionListResponse: {
            sessions: components["schemas"]["Session"][];
        };
        Session: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: date-time */
            expiresAt: string;
            userAgent?: string;
            current: boolean;
        };
        TOTPSetupResponse: {
            secret: string;
            /** Format: uri */
            provisioningUri: string;
        };
        TOTPConfirmRequest: {
            code: string;
        };
        TOTPConfirmResponse: {
            recoveryCodes: string[];
        };
        TOTPDisableRequest: {
            password: string;
            code: string;
        };
        UpdateProfileRequest: {
            /** Format: email */
            email: string;
            displayName: string;
            currentPassword?: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: components["schemas"]["Password"];
        };
        UpdateUserSettingsRequest: {
            timezone: string;
            functionalCurrency: components["schemas"]["Currency"];
            displayCurrency: components["schemas"]["Currency"];
            reconciliationMode: components["schemas"]["ReconciliationMode"];
        };
        DeleteAccountRequest: {
            password: string;
        };
        CompleteOnboardingRequest: {
            timezone: string;
            functionalCurrency: components["schemas"]["Currency"];
            displayCurrency: components["schemas"]["Currency"];
            reconciliationMode: components["schemas"]["ReconciliationMode"];
            account: components["schemas"]["OnboardingAccount"];
            recurringIncome?: components["schemas"]["OnboardingRecurringIncome"];
        };
        OnboardingAccount: {
            name: string;
            /** @enum {string} */
            accountClass: "ASSET" | "LIABILITY";
            /** @enum {string} */
            subtype: "bank" | "cash" | "brokerage" | "real_estate" | "vehicle" | "security" | "mortgage" | "loan" | "other";
            currency: components["schemas"]["Currency"];
            openingBalance: components["schemas"]["DecimalAmount"];
            /** Format: date */
            openingBalanceDate: string;
        };
        OnboardingRecurringIncome: {
            name: string;
            amount: components["schemas"]["PositiveDecimalAmount"];
            currency: components["schemas"]["Currency"];
            dayOfMonth: number;
        };
        CompleteOnboardingResponse: {
            user: components["schemas"]["User"];
            /** Format: uuid */
            accountSetupId: string;
            /** Format: uuid */
            recurringIncomeSetupId?: string;
        };
        AccountListResponse: {
            accounts: components["schemas"]["Account"][];
        };
        Account: {
            /** Format: uuid */
            id: string;
            name: string;
            accountClass: components["schemas"]["UserAccountClass"];
            subtype: components["schemas"]["AccountSubtype"];
            currency: components["schemas"]["Currency"];
            balance: components["schemas"]["DecimalAmount"];
            archived: boolean;
            hasPostings: boolean;
        };
        CreateAccountRequest: {
            name: string;
            accountClass: components["schemas"]["UserAccountClass"];
            subtype: components["schemas"]["AccountSubtype"];
            currency: components["schemas"]["Currency"];
            openingBalance?: components["schemas"]["DecimalAmount"];
            /** Format: date */
            openingBalanceDate?: string;
            /** Format: uuid */
            idempotencyKey?: string;
        };
        UpdateAccountRequest: {
            name?: string;
            currency?: components["schemas"]["Currency"];
            archived?: boolean;
        };
        CategoryListResponse: {
            categories: components["schemas"]["Category"][];
        };
        Category: {
            /** Format: uuid */
            id: string;
            name: string;
            direction: components["schemas"]["CategoryDirection"];
            archived: boolean;
        };
        CreateCategoryRequest: {
            name: string;
            direction: components["schemas"]["CategoryDirection"];
        };
        UpdateCategoryRequest: {
            name?: string;
            archived?: boolean;
        };
        /** @description Typed operation contract. Raw journal entries are never accepted from clients. */
        CreateTransactionRequest: {
            /** @enum {string} */
            type: "OPENING_BALANCE" | "INCOME" | "EXPENSE" | "TRANSFER" | "ASSET_PURCHASE";
            /** Format: date */
            eventDate: string;
            amount: components["schemas"]["PositiveDecimalAmount"];
            /** Format: uuid */
            idempotencyKey: string;
            description?: string;
            /**
             * Format: uuid
             * @description Required for opening balance, income, and expense.
             */
            accountId?: string;
            /**
             * Format: uuid
             * @description Required for income and expense.
             */
            categoryId?: string;
            /**
             * Format: uuid
             * @description Required for transfer and asset purchase.
             */
            sourceAccountId?: string;
            /**
             * Format: uuid
             * @description Required for transfer and asset purchase.
             */
            destinationAccountId?: string;
        };
        TransactionListResponse: {
            transactions: components["schemas"]["Transaction"][];
            nextCursor?: string;
        };
        Transaction: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["TransactionType"];
            /** Format: date */
            eventDate: string;
            description?: string;
            amount: components["schemas"]["PositiveDecimalAmount"];
            currency: components["schemas"]["Currency"];
            primaryAccountName: string;
            /** Format: uuid */
            primaryAccountId?: string;
            counterpartyName?: string;
            /** Format: uuid */
            counterpartyAccountId?: string;
            categoryName?: string;
            /** Format: uuid */
            categoryId?: string;
            /** @enum {string} */
            status: "POSTED" | "REVERSED" | "REVERSAL" | "REPLACED";
            /** Format: uuid */
            reversesTransactionId?: string;
            /** Format: uuid */
            replacesTransactionId?: string;
            /** Format: date-time */
            postedAt: string;
        };
        ReversalRequest: {
            /** Format: uuid */
            idempotencyKey: string;
            description?: string;
        };
        ReplacementRequest: {
            /** Format: uuid */
            reversalIdempotencyKey: string;
            operation: components["schemas"]["CreateTransactionRequest"];
        };
        ReplacementResponse: {
            reversal: components["schemas"]["Transaction"];
            replacement: components["schemas"]["Transaction"];
        };
        RecurringTemplateListResponse: {
            templates: components["schemas"]["RecurringTemplate"][];
        };
        RecurringTemplate: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["RecurringOperationType"];
            amount: components["schemas"]["PositiveDecimalAmount"];
            currency: components["schemas"]["Currency"];
            description?: string;
            /** Format: uuid */
            accountId?: string;
            accountName?: string;
            /** Format: uuid */
            categoryId?: string;
            categoryName?: string;
            /** Format: uuid */
            sourceAccountId?: string;
            sourceAccountName?: string;
            /** Format: uuid */
            destinationAccountId?: string;
            destinationAccountName?: string;
            frequency: components["schemas"]["RecurringFrequency"];
            intervalUnit: components["schemas"]["RecurringIntervalUnit"];
            intervalCount: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            nextScheduledDate: string;
            /** Format: date */
            endDate?: string;
            /** Format: date */
            lastGeneratedDate?: string;
            status: components["schemas"]["RecurringTemplateStatus"];
            pauseReason?: string;
            archived: boolean;
        };
        CreateRecurringTemplateRequest: {
            name: string;
            type: components["schemas"]["RecurringOperationType"];
            amount: components["schemas"]["PositiveDecimalAmount"];
            description?: string;
            /** Format: uuid */
            accountId?: string;
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            sourceAccountId?: string;
            /** Format: uuid */
            destinationAccountId?: string;
            frequency: components["schemas"]["RecurringFrequency"];
            intervalUnit?: components["schemas"]["RecurringIntervalUnit"];
            intervalCount?: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate?: string;
        };
        UpdateRecurringTemplateRequest: {
            name?: string;
            amount?: components["schemas"]["PositiveDecimalAmount"];
            description?: string;
            /** Format: date */
            endDate?: string;
            status?: components["schemas"]["RecurringTemplateStatus"];
            archived?: boolean;
        };
        ReconciliationStatus: {
            /** Format: date */
            today: string;
            /** Format: date */
            suggestedPeriodEnd: string;
            /** Format: date */
            periodEnd: string;
            promptOpen: boolean;
            /** Format: date */
            promptStart: string;
            /** Format: date */
            promptEnd: string;
            complete: boolean;
            accounts: components["schemas"]["AccountReconciliationStatus"][];
        };
        AccountReconciliationStatus: {
            /** Format: uuid */
            accountId: string;
            accountName: string;
            currency: components["schemas"]["Currency"];
            ledgerBalance: components["schemas"]["DecimalAmount"];
            /** @enum {string} */
            status: "PENDING" | "RECONCILED";
            reportedBalance?: components["schemas"]["DecimalAmount"];
            difference?: components["schemas"]["DecimalAmount"];
            /** Format: uuid */
            reconciliationId?: string;
            /** Format: date */
            lastReconciledPeriodEnd?: string;
            gapMonths: number;
            multiMonthGap: boolean;
        };
        PrepareReconciliationRequest: {
            /** Format: uuid */
            accountId: string;
            /** Format: date */
            periodEnd: string;
            reportedBalance: components["schemas"]["DecimalAmount"];
            /** Format: uuid */
            idempotencyKey: string;
        };
        ReconciliationSubmissionResponse: {
            /** @enum {string} */
            outcome: "PREVIEW" | "APPLIED";
            preview?: components["schemas"]["ReconciliationPreview"];
            reconciliation?: components["schemas"]["Reconciliation"];
        };
        ReconciliationPreview: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            accountId: string;
            accountName: string;
            currency: components["schemas"]["Currency"];
            /** Format: date */
            periodEnd: string;
            reportedBalance: components["schemas"]["DecimalAmount"];
            ledgerBalance: components["schemas"]["DecimalAmount"];
            difference: components["schemas"]["DecimalAmount"];
            /** @enum {string} */
            direction: "OTHER_INCOME" | "OTHER_EXPENSE" | "NONE";
            gapMonths: number;
            multiMonthGap: boolean;
            /** Format: date-time */
            expiresAt: string;
        };
        Reconciliation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            accountId: string;
            accountName: string;
            currency: components["schemas"]["Currency"];
            /** Format: date */
            periodEnd: string;
            reportedBalance: components["schemas"]["DecimalAmount"];
            ledgerBalanceBefore: components["schemas"]["DecimalAmount"];
            difference: components["schemas"]["DecimalAmount"];
            adjustmentAmount: components["schemas"]["DecimalAmount"];
            /** Format: uuid */
            adjustmentTransactionId?: string;
            /** Format: uuid */
            reversalTransactionId?: string;
            /** Format: uuid */
            supersedesReconciliationId?: string;
            /** Format: date */
            gapStartPeriodEnd?: string;
            gapMonths: number;
            multiMonthGap: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        AssetListResponse: {
            assets: components["schemas"]["Asset"][];
            totalCurrentOwnedValue: components["schemas"]["DecimalAmount"];
            allocations: components["schemas"]["AssetAllocation"][];
        };
        AssetAllocation: {
            type: components["schemas"]["AssetType"];
            currentOwnedValue: components["schemas"]["DecimalAmount"];
        };
        Asset: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["AssetType"];
            currency: components["schemas"]["Currency"];
            ownershipShare: components["schemas"]["OwnershipShare"];
            country?: string;
            region?: string;
            institution?: string;
            notes?: string;
            /** Format: uuid */
            ledgerAccountId: string;
            ledgerAccountName: string;
            ledgerBalance: components["schemas"]["DecimalAmount"];
            currentOwnedValue: components["schemas"]["DecimalAmount"];
            latestMarketValue?: components["schemas"]["DecimalAmount"];
            /** Format: date */
            latestValuationDate?: string;
            /** Format: uuid */
            purchaseTransactionId?: string;
            archived: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        CreateAssetPurchase: {
            /** Format: uuid */
            sourceAccountId: string;
            amount: components["schemas"]["PositiveDecimalAmount"];
            /** Format: date */
            eventDate: string;
            description?: string;
        };
        CreateAssetRequest: {
            name: string;
            type: components["schemas"]["AssetType"];
            currency: components["schemas"]["Currency"];
            ownershipShare: components["schemas"]["OwnershipShare"];
            country?: string;
            region?: string;
            institution?: string;
            notes?: string;
            /**
             * Format: uuid
             * @description Optional existing private asset account. A dedicated account is created when omitted.
             */
            ledgerAccountId?: string;
            purchase?: components["schemas"]["CreateAssetPurchase"];
            /** Format: uuid */
            idempotencyKey: string;
        };
        UpdateAssetRequest: {
            name?: string;
            country?: string;
            region?: string;
            institution?: string;
            notes?: string;
            archived?: boolean;
        };
        AssetValuationListResponse: {
            valuations: components["schemas"]["AssetValuation"][];
        };
        AssetValuation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            assetId: string;
            /** Format: date */
            valuationDate: string;
            marketValue: components["schemas"]["DecimalAmount"];
            ownedValue: components["schemas"]["DecimalAmount"];
            ledgerBalanceBefore: components["schemas"]["DecimalAmount"];
            adjustmentAmount: components["schemas"]["DecimalAmount"];
            notes?: string;
            /** Format: uuid */
            revaluationTransactionId?: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateAssetValuationRequest: {
            /** Format: date */
            valuationDate: string;
            marketValue: components["schemas"]["DecimalAmount"];
            notes?: string;
            /** Format: uuid */
            idempotencyKey: string;
        };
        /** @enum {string} */
        AssetType: "REAL_ESTATE" | "VEHICLE" | "BUSINESS" | "SECURITIES" | "COLLECTIBLES" | "OTHER";
        OwnershipShare: string;
        /** @enum {string} */
        RecurringOperationType: "INCOME" | "EXPENSE" | "TRANSFER" | "ASSET_PURCHASE";
        /** @enum {string} */
        RecurringFrequency: "WEEKLY" | "MONTHLY" | "QUARTERLY" | "YEARLY" | "CUSTOM";
        /** @enum {string} */
        RecurringIntervalUnit: "DAYS" | "WEEKS" | "MONTHS" | "YEARS";
        /** @enum {string} */
        RecurringTemplateStatus: "ACTIVE" | "PAUSED";
        /** @enum {string} */
        UserAccountClass: "ASSET" | "LIABILITY";
        /** @enum {string} */
        AccountSubtype: "bank" | "cash" | "brokerage" | "real_estate" | "vehicle" | "security" | "mortgage" | "loan" | "other";
        /** @enum {string} */
        CategoryDirection: "INCOME" | "EXPENSE";
        /** @enum {string} */
        TransactionType: "OPENING_BALANCE" | "INCOME" | "EXPENSE" | "TRANSFER" | "ASSET_PURCHASE" | "RECONCILIATION" | "REVALUATION" | "REVERSAL";
        Password: string;
        DecimalAmount: string;
        PositiveDecimalAmount: string;
        /** @enum {string} */
        ReconciliationMode: "AUTO" | "CONFIRM";
        /** @enum {string} */
        Currency: "USD" | "EUR" | "JPY" | "GBP" | "CNY" | "AUD" | "CAD" | "CHF" | "HKD" | "SGD" | "SEK" | "KRW" | "NOK" | "NZD" | "INR" | "MXN" | "TWD" | "ZAR" | "BRL" | "DKK" | "UAH" | "KZT" | "RUB" | "AED";
    };
    responses: {
        /** @description Request validation failed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication or credential verification failed */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource state conflicts with the request */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Owned resource was not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Too many attempts */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Required dependency unavailable */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        AccountId: string;
        CategoryId: string;
        TransactionId: string;
        TemplateId: string;
        PreviewId: string;
        AssetId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API and database are ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getDashboard: {
        parameters: {
            query?: {
                /** @description Calendar month used for income, expenses, and savings, formatted YYYY-MM. */
                month?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard metrics, chart series, and FX freshness state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Identity and session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session created because TOTP is disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Password accepted and a one-time TOTP challenge was created */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginChallengeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    verifyLoginTOTP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TOTPLoginRequest"];
            };
        };
        responses: {
            /** @description Authenticator code accepted and session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    verifyLoginRecoveryCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryLoginRequest"];
            };
        };
        responses: {
            /** @description Recovery code consumed and session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Browser session revoked or already absent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    setupTOTP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending TOTP credential created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TOTPSetupResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    confirmTOTP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TOTPConfirmRequest"];
            };
        };
        responses: {
            /** @description TOTP enabled and recovery codes returned once */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TOTPConfirmResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    disableTOTP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TOTPDisableRequest"];
            };
        };
        responses: {
            /** @description TOTP and recovery codes removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description User and owned data deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed and other sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    updateUserSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserSettingsRequest"];
            };
        };
        responses: {
            /** @description Updated settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteOnboardingRequest"];
            };
        };
        responses: {
            /** @description Onboarding completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteOnboardingResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    listAccounts: {
        parameters: {
            query?: {
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owned accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description Account updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owned categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        responses: {
            /** @description Category updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                accountId?: string;
                categoryId?: string;
                type?: components["schemas"]["TransactionType"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable operation page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Operation posted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    reverseTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transactionId: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReversalRequest"];
            };
        };
        responses: {
            /** @description Reversal posted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    replaceTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transactionId: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplacementRequest"];
            };
        };
        responses: {
            /** @description Original reversed and corrected operation posted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplacementResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listRecurringTemplates: {
        parameters: {
            query?: {
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recurring templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringTemplateListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createRecurringTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecurringTemplateRequest"];
            };
        };
        responses: {
            /** @description Recurring template created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringTemplate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    updateRecurringTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecurringTemplateRequest"];
            };
        };
        responses: {
            /** @description Recurring template updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringTemplate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getReconciliationStatus: {
        parameters: {
            query?: {
                periodEnd?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reconciliation status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationStatus"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    prepareReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrepareReconciliationRequest"];
            };
        };
        responses: {
            /** @description Preview created or reconciliation applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationSubmissionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    confirmReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                previewId: components["parameters"]["PreviewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reconciliation applied */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reconciliation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listAssets: {
        parameters: {
            query?: {
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset profiles and allocation inputs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetRequest"];
            };
        };
        responses: {
            /** @description Asset profile created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAssetRequest"];
            };
        };
        responses: {
            /** @description Asset profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listAssetValuations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset valuation history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetValuationListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createAssetValuation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetValuationRequest"];
            };
        };
        responses: {
            /** @description Valuation snapshot recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetValuation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
